# Generated by Django 2.1 on 2018-08-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_email', models.CharField(max_length=200)),
                ('agent_squire_id', models.CharField(max_length=200)),
            ],
        ),
    ]
