# Generated by Django 2.1 on 2018-08-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_name',
        ),
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default='null', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_squire_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='media/'),
        ),
    ]
