# Generated by Django 2.1 on 2018-08-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180828_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agent_squire_id',
        ),
    ]
