# Generated by Django 2.1 on 2018-08-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180828_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_name',
        ),
    ]
