# Generated by Django 2.1 on 2018-08-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_owner',
            new_name='owner',
        ),
    ]
