# Generated by Django 2.1 on 2018-08-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20180829_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_updated',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
