# Generated by Django 2.1 on 2018-08-30 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='timestamp_created',
        ),
        migrations.AddField(
            model_name='ticket',
            name='dttm_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='dttm_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
