# Generated by Django 2.1 on 2018-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20180906_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
